AWSTemplateFormatVersion: '2010-09-09'

Description: CloudMart Event Driven Low Stock Alert Stack

Parameters:

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  LowStockEmail:
    Type: String

Resources:

  CloudMartEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub cloudmart-${Environment}-event-bus

  LowStockEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub cloudmart-${Environment}-low-stock-rule
      EventBusName: !Ref CloudMartEventBus
      State: ENABLED

      EventPattern:
        source:
          - cloudmart.product
        detail-type:
          - Low Stock Alert

      Targets:
        - Id: LowStockSNSTarget
          Arn:
            Fn::ImportValue:
              !Sub CloudMart-${Environment}-LowStockTopicArn

  LowStockSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - Fn::ImportValue:
            !Sub CloudMart-${Environment}-LowStockTopicArn

      PolicyDocument:
        Version: '2012-10-17'

        Statement:
          - Sid: AllowEventBridgePublish
            Effect: Allow

            Principal:
              Service:
                - events.amazonaws.com

            Action:
              - sns:Publish

            Resource:
              Fn::ImportValue:
                !Sub CloudMart-${Environment}-LowStockTopicArn

Outputs:

  CloudMartEventBusArn:
    Value: !GetAtt CloudMartEventBus.Arn
    Export:
      Name: !Sub CloudMart-${Environment}-EventBusArn

  CloudMartEventBusName:
    Value: !Ref CloudMartEventBus
    Export:
      Name: !Sub CloudMart-${Environment}-EventBusName

  LowStockRuleArn:
    Value: !GetAtt LowStockEventRule.Arn
    Export:
      Name: !Sub CloudMart-${Environment}-LowStockRuleArn