permissions:
  id-token: write
  contents: read

jobs:

  deploy-iam:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show GitHub OIDC information
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Full ref: $GITHUB_REF"
          echo "Repository ID: $GITHUB_REPOSITORY_ID"
          echo "Repository owner ID: $GITHUB_REPOSITORY_OWNER_ID"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}