name: CloudMart Infrastructure

on:
  workflow_dispatch:
    inputs:
      operations_cidr:
        description: "Public IP/CIDR allowed to access the CloudMart dashboard"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:

  deploy-network:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1


      - name: Verify AWS access
        run: |
          aws sts get-caller-identity


      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://cloudformation/network/network-stack.yaml \
            --region ap-south-1


      - name: Deploy Network Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/network/network-stack.yaml \
            --stack-name cloudmart-dev-network \
            --parameter-overrides \
              Environment=dev \
              OperationsCidr="${{ inputs.operations_cidr }}" \
            --region ap-south-1


      - name: Check Stack Status
        run: |
          aws cloudformation describe-stacks \
            --stack-name cloudmart-dev-network \
            --region ap-south-1