name: CloudMart Lambda Artifact Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ENVIRONMENT: dev

jobs:

  deploy-artifact:
    name: Deploy Lambda Artifact Bucket
    runs-on: ubuntu-latest

    steps:

      # --------------------------------------------------------
      # Checkout
      # --------------------------------------------------------

      - name: Checkout repository
        uses: actions/checkout@v4


      # --------------------------------------------------------
      # Configure AWS credentials
      # --------------------------------------------------------

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}


      # --------------------------------------------------------
      # Verify AWS access
      # --------------------------------------------------------

      - name: Verify AWS access
        run: |
          aws sts get-caller-identity


      # --------------------------------------------------------
      # Validate CloudFormation
      # --------------------------------------------------------

      - name: Validate Artifact CloudFormation
        run: |
          aws cloudformation validate-template \
            --template-body file://cloudformation/artifact/artifact-stack.yaml \
            --region "${AWS_REGION}"


      # --------------------------------------------------------
      # Deploy Artifact Stack
      # --------------------------------------------------------

      - name: Deploy Artifact Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/artifact/artifact-stack.yaml \
            --stack-name cloudmart-dev-artifact \
            --parameter-overrides \
              Environment="${ENVIRONMENT}" \
            --region "${AWS_REGION}"


      # --------------------------------------------------------
      # Check Stack
      # --------------------------------------------------------

      - name: Check Artifact Stack
        run: |
          aws cloudformation describe-stacks \
            --stack-name cloudmart-dev-artifact \
            --region "${AWS_REGION}" \
            --query "Stacks[0].StackStatus" \
            --output text


      # --------------------------------------------------------
      # Display Bucket Name
      # --------------------------------------------------------

      - name: Display Artifact Bucket
        run: |
          echo "Lambda Artifact Bucket:"

          aws cloudformation describe-stacks \
            --stack-name cloudmart-dev-artifact \
            --region "${AWS_REGION}" \
            --query "Stacks[0].Outputs[?OutputKey=='LambdaArtifactBucketName'].OutputValue" \
            --output text